[package]
name = "advantofcode-01"
version = "0.1.0"
authors = ["____marcell <0000marcell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
